### PR TITLE
feat: 新增 Logo 控件

### PR DESCRIPTION
**Pull request by zhaoqc-max**
### 新增logo控件
新增： logo控件

### Screenshot

| Before | After |
| ------ | 
 |
| ❌     | ✅ |

### CODE REVIEW

**Comment by lvisei** [comment]
image

换个名字

**Comment by lvisei** [comment]
考虑是不是与 AttributionControl 定位一致

- https://github.com/visgl/react-map-gl/issues/1129
- https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol
- https://docs.mapbox.com/help/getting-started/attribution/

**Review by lvisei — COMMENTED** [review]
考虑是不是与 AttributionControl 定位一致

- https://github.com/visgl/react-map-gl/issues/1129
[docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol]

- (https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol)
[docs.mapbox.com/help/getting-started/attribution]

- (https://docs.mapbox.com/help/getting-started/attribution/)

**Comment by heiyexing** [comment]
> image
> 
> 换个名字



> image
> 
> 换个名字

>  改成 “徽标” 把

**Review by lvisei — APPROVED** [review]

**Pull request merged**
